### ISSUE TITLE
GMail requires base64.URLEncoding, not base64.StdEncoding

### ISSUE THREAD

**Issue by andlabs** [xDinomode/Go-Gmail-Api-Example#1]
This is an issue both in the blog post and in this repo: if just the right email is prepared, `base64.StdEncoding` will produce something that will result in GMail complaining with `Error 400: Invalid value for ByteString`. GMail [uses base64url, not the standard base64 encoding](https://developers.google.com/gmail/api/v1/reference/users/messages/send#request-body), so `base64.URLEncoding` must be used instead.

Thanks for the post in the meantime; it was quite helpful!

**Comment by xDinomode** [comment]
Alright just committed your fix. Thank you.
